server.port=8082

spring.application.name=talkmanager
spring.datasource.url=jdbc:postgresql://localhost:5432/talkmanager
spring.datasource.username=postgres
spring.datasource.password=new_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
